# Generated by Django 3.1.3 on 2021-03-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0002_fone_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('voluntariado_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_voluntariado', models.CharField(max_length=100)),
                ('desc_voluntariado', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntariados', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'Voluntariado',
                'verbose_name_plural': 'Voluntariados',
            },
        ),
    ]
